export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  content: string[]; // paragraphs; strings starting with "## " render as headings
};

export const posts: BlogPost[] = [
  {
    slug: "how-gold-rates-are-determined-in-pakistan",
    title: "How Gold Rates Are Determined in Pakistan (and Why They Change Daily)",
    description: "A plain-language look at why gold prices in Pakistan move every day, and what actually drives the number your local jeweller quotes.",
    date: "2026-07-20",
    readTime: "4 min read",
    content: [
      "If you've ever wondered why the gold rate posted outside your local jeweller's shop seems to change almost every day, the answer has less to do with local demand and more to do with global markets thousands of miles away.",
      "## The international spot price",
      "Gold is traded globally in US dollars per troy ounce, on markets like COMEX and the London Bullion Market. This international spot price moves constantly during trading hours, reacting to inflation data, central bank policy, geopolitical tension, and investor sentiment. Pakistan doesn't set its own independent gold price — it imports the international rate and converts it.",
      "## The currency conversion layer",
      "Since the global price is in USD, it has to be converted into PKR. This means two things move the local rate at once: the international gold price itself, and the USD to PKR exchange rate. A weaker rupee, even with a flat international gold price, will push the local rate higher — which is part of why gold has felt like a one-way bet for many Pakistani savers over the past few years.",
      "## The local premium",
      "On top of the converted international price, the All Pakistan Sarafa Gems and Jewellers Association typically factors in import duties, local market conditions, and a small premium. This is why the officially notified 'Sarafa rate' can differ slightly from what an individual shop quotes, especially for jewellery versus raw bullion.",
      "## What this means for you",
      "If you're buying or selling gold, checking the rate right before your transaction matters — rates can shift meaningfully within a single day during volatile periods. You can check today's converted rate, along with a gram-to-tola breakdown, on our Rates page.",
    ],
  },
  {
    slug: "complete-guide-to-zakat-calculation",
    title: "A Complete Guide to Calculating Your Zakat",
    description: "Understand Nisab, what counts as zakatable wealth, and how to calculate the 2.5% due — with a worked example.",
    date: "2026-07-18",
    readTime: "5 min read",
    content: [
      "Zakat is one of the five pillars of Islam, and for many Muslims, the hardest part isn't the intention — it's actually working out the number. Here's a straightforward walkthrough.",
      "## What counts as zakatable wealth",
      "Broadly: cash and bank savings, gold and silver you own, business inventory, and investments held for growth. It does not typically include your home, car, or personal-use items like furniture and clothing.",
      "## The Nisab threshold",
      "You only owe Zakat if your total zakatable wealth, held for one full lunar (Hijri) year, meets or exceeds the Nisab — commonly calculated as the value of 87.48 grams of gold (or, in some interpretations, 612.36 grams of silver, which usually results in a lower threshold).",
      "## The calculation",
      "Once you're above Nisab, Zakat is 2.5% of your total zakatable wealth, minus any short-term debts you owe. So: (Cash + Gold value + Business assets − Debts) × 2.5%.",
      "## A worked example",
      "Say you have Rs 500,000 in savings, no gold, and Rs 50,000 in short-term debt. Zakatable wealth = 500,000 − 50,000 = 450,000. If that exceeds Nisab, Zakat due = 450,000 × 0.025 = Rs 11,250.",
      "Use our Zakat Calculator to run your own numbers automatically, using today's gold price for the Nisab threshold.",
    ],
  },
  {
    slug: "how-to-check-bisp-8171-status-safely",
    title: "How to Check Your BISP 8171 Status Safely (and Avoid Scam Sites)",
    description: "The two official ways to check your BISP Ehsaas status, and the warning signs of fake '8171 checker' websites.",
    date: "2026-07-15",
    readTime: "3 min read",
    content: [
      "The 8171 program is one of the most-searched terms in Pakistan every month, and unfortunately, that popularity has attracted a wave of look-alike websites that aren't official.",
      "## The two legitimate methods",
      "First: SMS your 13-digit CNIC (no dashes) to 8171 and wait for the automated reply. Second: use the official BISP web portal directly, typing the URL in yourself rather than clicking a link from social media.",
      "## Red flags to watch for",
      "Be cautious of any site that asks for more than your CNIC — phone number, bank account details, or a 'processing fee' to release your payment. BISP does not charge a fee to check eligibility or release funds. Sites with urgent countdown timers, requests to 'share to unlock,' or ads promising guaranteed approval are not official government channels.",
      "## Why this matters beyond your own data",
      "Entering your CNIC on an unofficial site doesn't just risk your own data — scam operators use harvested CNICs for further fraud attempts against you and people in your contact list. When in doubt, stick to the SMS method; it's simple, free, and impossible to spoof.",
    ],
  },
  {
    slug: "fpsc-vs-ppsc-vs-nts-explained",
    title: "FPSC vs PPSC vs NTS: What's the Difference, and Which Test Should You Take?",
    description: "A breakdown of Pakistan's three major public-sector testing bodies and what each one actually recruits for.",
    date: "2026-07-12",
    readTime: "4 min read",
    content: [
      "If you're starting your government job search, the alphabet soup of FPSC, PPSC, and NTS can be confusing. Here's how they actually differ.",
      "## FPSC — Federal Public Service Commission",
      "FPSC recruits for federal government positions, most famously the CSS (Central Superior Services) exam, along with various federal ministry and department roles. If the job is federal-level, FPSC is usually the gatekeeper.",
      "## PPSC — Punjab Public Service Commission",
      "PPSC handles recruitment specifically for provincial government positions within Punjab — everything from lecturer posts to administrative roles in Punjab departments. Other provinces have their own equivalent commissions (SPSC for Sindh, KPPSC for Khyber Pakhtunkhwa, BPSC for Balochistan).",
      "## NTS — National Testing Service",
      "NTS isn't a government commission itself — it's a testing service that many public and private organizations outsource their hiring tests to. If you see a job ad saying 'apply and appear for an NTS test,' the hiring organization is using NTS purely to administer the written exam, not necessarily a provincial or federal commission role.",
      "## Which one should you focus on?",
      "It depends entirely on the specific job you want, not a general preference — check the hiring organization's official advertisement to see which body is running that particular recruitment process.",
    ],
  },
  {
    slug: "students-guide-to-checking-matric-inter-results",
    title: "A Student's Guide to Checking Matric and Inter Results Online",
    description: "How Pakistan's BISE board result system works, and what to do if your result seems wrong.",
    date: "2026-07-10",
    readTime: "3 min read",
    content: [
      "Result day is stressful enough without also being confused about where to actually look. Here's how the system works.",
      "## Results are per-board, not national",
      "Pakistan doesn't have one central Matric/Inter results portal — each province has its own BISE (Board of Intermediate and Secondary Education), and your result is published by whichever board you're registered under (e.g., BISE Lahore, BISE Karachi). Always check your admit card to confirm which board you belong to.",
      "## What you'll need",
      "Your roll number, printed on your admit card/roll number slip, is the standard way to look up your result online. Some boards also support search by name and father's name as a backup.",
      "## If something looks wrong",
      "If your result seems inconsistent with your expectations, boards typically offer a rechecking (re-totaling) or remarking service within a set window after results are announced — this involves an official fee and a formal application through your board, not a phone call or informal request.",
      "## A quick tip",
      "Save or screenshot your result the day it's published — official portals can get overloaded with traffic and are sometimes temporarily unavailable in the first hours after an announcement.",
    ],
  },
  {
    slug: "7-tips-to-lower-your-electricity-bill",
    title: "7 Practical Tips to Lower Your Electricity Bill in Pakistan",
    description: "Realistic, low-cost changes that actually move the needle on a Pakistani household electricity bill.",
    date: "2026-07-08",
    readTime: "4 min read",
    content: [
      "With per-unit rates rising and slab pricing meaning consumption above certain thresholds costs disproportionately more, small changes can meaningfully reduce your bill.",
      "## 1. Understand your slab",
      "Because Pakistan's tariff is slab-based, using slightly less can sometimes drop you into a cheaper bracket entirely — not just save you the marginal units. Check where your usage sits relative to the nearest lower slab.",
      "## 2. Prioritize your AC usage",
      "Air conditioning is typically the single largest load in a Pakistani household during summer. Setting it to 26°C instead of 20°C, and using a timer instead of running it all night, can meaningfully cut consumption.",
      "## 3. Switch to LED lighting",
      "If you still have older bulbs, replacing them with LEDs is one of the fastest-paying-back changes you can make — LEDs use a fraction of the electricity for the same brightness.",
      "## 4. Unplug idle appliances",
      "Chargers, routers, and standby electronics draw small amounts of 'phantom' power continuously. It's a small effect per device but adds up across a household.",
      "## 5. Service your fridge and AC",
      "Dirty AC filters and fridge coils make the compressor work harder for the same cooling effect, quietly increasing your consumption over time.",
      "## 6. Shift heavy appliance use off-peak where applicable",
      "Some DISCOs and time-of-use plans charge differently by time of day — check whether shifting washing machine or iron use to off-peak hours applies to your connection.",
      "## 7. Estimate before you're surprised",
      "Use our Electricity Bill Estimator to project your bill from expected units and your current per-unit rate, so the number on the actual bill isn't a surprise.",
    ],
  },
  {
    slug: "understanding-usd-to-pkr-exchange-rate-movements",
    title: "Understanding USD to PKR Exchange Rate Movements",
    description: "What actually moves the dollar rate in Pakistan, in plain terms.",
    date: "2026-07-05",
    readTime: "4 min read",
    content: [
      "The USD to PKR rate affects everything from imported fuel prices to your relatives' remittances, but the 'why' behind its movement is rarely explained simply.",
      "## Supply and demand for dollars",
      "At the most basic level, the rate reflects how many people want to buy dollars versus sell them at a given moment. Importers need dollars to pay for foreign goods; exporters and remittance-senders bring dollars in. When demand for dollars outpaces supply, the rupee weakens.",
      "## The State Bank's role",
      "The State Bank of Pakistan (SBP) manages monetary policy and, at times, intervenes in the currency market to smooth out excessive volatility, though Pakistan has largely operated a market-determined exchange rate regime in recent years.",
      "## External factors",
      "Global oil prices matter a lot — Pakistan is a major fuel importer, so a spike in oil prices increases dollar demand just to keep imports flowing. IMF program reviews, foreign reserve levels, and political stability also feed directly into currency sentiment.",
      "## Why the interbank rate and your local exchange differ slightly",
      "The rate you see quoted online (like on our Rates page) usually reflects the interbank reference rate. Currency exchanges and banks add a small spread on top when you actually buy or sell, which is normal and part of how they cover operating costs.",
    ],
  },
  {
    slug: "how-to-renew-your-cnic-nadra-guide",
    title: "How to Renew Your CNIC: A Step-by-Step NADRA Guide",
    description: "The renewal process, documents needed, and fee tiers for Pakistan's national ID card.",
    date: "2026-07-02",
    readTime: "3 min read",
    content: [
      "Your CNIC has an expiry date, and letting it lapse can cause headaches for banking, travel, and government services. Here's the renewal process in plain steps.",
      "## Step 1: Check your expiry date",
      "It's printed directly on your CNIC. NADRA generally allows renewal applications within a window before expiry, so you don't need to wait until the last day.",
      "## Step 2: Choose your application channel",
      "You can apply at a NADRA Registration Center in person, or through NADRA's official online portal if you're eligible for the digital process, which typically still requires biometric verification at some point.",
      "## Step 3: Submit required documents",
      "Generally: your existing (or expired) CNIC, and a passport-size photograph if applying in person. Requirements can vary slightly depending on whether it's a straightforward renewal or involves any changes to your recorded information.",
      "## Step 4: Pay the applicable fee",
      "NADRA offers multiple processing speeds — normal, urgent, and executive — each at a different fee and turnaround time. Choose based on how quickly you need the card.",
      "## Step 5: Track your application",
      "Use the tracking ID issued at submission through NADRA's official SMS service or website. Never share this ID or your CNIC number with a third-party 'tracking' site.",
    ],
  },
  {
    slug: "passport-application-pakistan-documents-fees-timeline",
    title: "Passport Application in Pakistan: Documents, Fees, and Timeline",
    description: "What to prepare before you apply for a Pakistani passport, and realistic timelines by processing tier.",
    date: "2026-06-28",
    readTime: "3 min read",
    content: [
      "Whether it's your first passport or a renewal, knowing what to expect going in saves you a wasted trip to the Passport Office.",
      "## Documents you'll typically need",
      "Your CNIC (valid, not expired), your previous passport if renewing, and any category-specific documents (e.g., for minors, additional parental documentation is usually required).",
      "## Choosing a processing tier",
      "DGIP typically offers normal, urgent, and executive processing, each with a different fee and turnaround — urgent and executive tiers cost more but significantly cut the wait time, which matters if you have imminent travel plans.",
      "## Booking your appointment",
      "Applications are generally submitted through the official online portal, where you'll also book a time slot at your chosen Passport Office to submit biometrics.",
      "## After submission",
      "You'll receive a tracking ID to monitor your application status online. If your passport doesn't arrive within the expected window for your tier, contact the Passport Office directly rather than relying on unofficial 'status check' websites.",
    ],
  },
  {
    slug: "job-hunting-in-pakistans-government-sector",
    title: "Best Practices for Job Hunting in Pakistan's Government Sector",
    description: "Practical advice for navigating FPSC, PPSC, and NTS recruitment cycles without missing deadlines.",
    date: "2026-06-25",
    readTime: "4 min read",
    content: [
      "Government recruitment in Pakistan runs on its own rhythm — different from private-sector hiring — and understanding that rhythm helps you avoid missing your shot.",
      "## Know your commission",
      "Figure out early whether the role you want falls under FPSC (federal), your provincial commission (PPSC, SPSC, KPPSC, BPSC), or is administered via NTS on behalf of another organization. Each publishes its own advertisement schedule and eligibility criteria.",
      "## Track advertisement cycles",
      "Government job ads tend to cluster around certain times of year and specific application windows that can be as short as two to three weeks. Missing the window usually means waiting for the next cycle, sometimes months later.",
      "## Prepare documents in advance",
      "Domicile certificates, updated CNIC, educational certificates, and experience letters take time to gather. Having them ready before an ad drops means you're not scrambling during a short application window.",
      "## Understand the test structure",
      "Most public-sector recruitment involves a written test, and for higher-tier posts, an interview stage. Past papers (where officially available) and the syllabus published with the job advertisement are your most reliable prep resources — be wary of unofficial 'guaranteed pass' guides.",
      "## Keep a checklist",
      "Track application deadlines, test dates, and result dates across the organizations you're applying to — it's common to be in multiple recruitment pipelines simultaneously, and overlapping dates can catch people off guard.",
    ],
  },
];

export function getPostBySlug(slug: string) {
  return posts.find((p) => p.slug === slug);
}
